name: Build Jekyll page, generate PDF, and deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v2
        with:
          path: _vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      
      - name: Build with Jekyll
        uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          repository: 'lanzac/cv'
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          ruby_ver:
          bundler_ver:        # Default is latest bundler version
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux) 

        # Generate the PDF in English
      - name: Generate en-us PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: _site/index.html
          outputFile: resume_en-us.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      # Generate the PDF in French
      - name: Generate fr-fr PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: _site/fr-fr/index.html
          outputFile: resume_fr-fr.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      - name: Deploy to GitHub Pages
        uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          repository: 'lanzac/cv'
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          ruby_ver: '3.2.2'
          bundler_ver: '2.4.19'         # Default is latest bundler version
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux) 
