# Site settings
title: "André Lanrezac CV"
description: "André Lanrezac Curriculum vitæ"

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------
# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Includes & excludes
include: ["_pages"]

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - README_template.md
  - vendor

keep_files:
  - CNAME

# -----------------------------------------------------------------------------
# Jekyll Polyglot
# -----------------------------------------------------------------------------
# https://github.com/untra/polyglot

plugins:
  - jekyll-polyglot

languages: ["en-us", "fr-fr"]
default_lang: "en-us"
exclude_from_localizations: ["assets"]
parallel_localization: true
baseurl: "/cv"

# Resume settings
resume_avatar:                  "true"
resume_name:                    "André Lanrezac"
resume_title:                   "Curriculum vitæ"
display_resume_title:           "false"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "a.lanrezac@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+33) 665375668"
resume_contact_address:         ""

resume_header_contact_info:     "(+33) 665375668 • a.lanrezac@gmail.com"
display_header_contact_info:    "false"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_softwares:       true
resume_section_interests:       true
resume_section_publications:    true


# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/lanzac"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/andre-lanrezac"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
  resume_researchgate_url:      "https://www.researchgate.net/profile/Andre-Lanrezac"
  resume_orcid_url:             "https://orcid.org/0000-0003-2069-4161"
  resume_mail_url:              "a.lanrezac@gmail.com"
  # resume_tel:                   ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
