lang_name: "EN"

resume_status: "Bioinformatician | Scientific Developer"

resume_section_experience_title:     "Experience"
resume_section_education_title:      "Education"
resume_section_projects_title:       "Projects"
resume_section_skills_title:         "Skills"
resume_section_recognition_title:    "Recognition"
resume_section_links_title:          "Additional Links"
resume_section_associations_title:   "Associations"
resume_section_softwares_title:      "Softwares & Tools"
resume_section_interests_title:      "Outside Interests"
resume_section_publications_title:   "Publications & scientific production"
resume_section_social_links_title:   "Social Links"

resume_header_intro: >
  <p>I am a bioinformatician specialized in structural bioinformatics and large-scale simulations,
  working at the intersection of physics, chemistry, and computer science.
  I have particularly focused on developing and implementing a comprehensive software suite
  for interactive molecular simulations (IMS), enabling real-time human interaction with ongoing
  simulations, especially for studying the insertion profile of membrane proteins.
  Currently, I am further specializing as a scientific developer, enhancing my skills
  in software engineering, in particular software architecture.</p>


resume_printed_resume_link: "The maintained version is accessible online at https://lanzac.github.io/cv/"

intro_section_software: >
  <p>
    I pursued the development of BioSpring, UnityMol and MDDriver during my thesis, and they are currently my side project.
    These are projects developed by Marc Baaden's team at the Theoretical Biochemistry Laboratory.
  </p>