name: Build Jekyll page, generate PDF, and deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Ruby
      - name: Install asdf
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.12.0
          echo ". $HOME/.asdf/asdf.sh" >> $GITHUB_ENV
          echo ". $HOME/.asdf/completions/asdf.bash" >> $GITHUB_ENV
      
      - name: Install asdf Ruby plugin
        run: |
          source $HOME/.asdf/asdf.sh
          asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git

      - name: Install Ruby
        run: |
          source $HOME/.asdf/asdf.sh
          asdf install ruby 3.2.2
          asdf global ruby 3.2.2

      - name: Check Ruby version
        run: ruby -v
      # ------------------------------------------------------------------------
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll (Test)
        uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          repository: 'lanzac/cv'
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          ruby_ver:
          bundler_ver:        # Default is latest bundler version
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux) 

        # Generate the PDF in English
      - name: Generate en-us PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: _site/index.html
          outputFile: _site/resume_en-us.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      # Generate the PDF in French
      - name: Generate fr-fr PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: _site/fr-fr/index.html
          outputFile: _site/fr-fr/resume_fr-fr.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      - name: Upload _site as artifact
        uses: actions/upload-artifact@v3
        with:
          name: site_files


  # Job 3: Deploy the site with PDFs to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download site with PDFs
        uses: actions/download-artifact@v3
        with:
          name: site_files

      - name: List _site contents after PDFs
        run: ls -R _site

      - name: Deploy to GitHub Pages
        uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          repository: 'lanzac/cv'
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          ruby_ver: '3.2.2'
          bundler_ver: '2.4.19'         # Default is latest bundler version
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux) 
